---

- name: add pycharm repo to deb list
  apt_repository:
    repo: deb http://archive.getdeb.net/ubuntu yakkety-getdeb apps
    state: present 

- name: add keyring for pycharm repo
  apt_key:
    url: http://archive.getdeb.net/getdeb-archive.key
    state: present

- name: install pycharm
  apt:
    name: pycharm
    state: latest
    force: yes
    update_cache: yes

- name: remove pycharm repo to deb list due to bugs in KVM virt-manager
  apt_repository:
    repo: deb http://archive.getdeb.net/ubuntu yakkety-getdeb apps
    state: absent 
