language: python
python: "2.7"

sudo: enabled
dist: xenial

env:
  - ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then sudo pip install ansible; else sudo pip install ansible==$ANSIBLE_VERSION; fi
  # Mock ansible.cfg
  - sudo mkdir -p /etc/ansible
  - sudo adduser --disabled-password --gecos "" hf
  - sudo echo "" | sudo tee --append /etc/ansible/ansible.cfg

script:
  - sudo ansible-playbook -i inventory/hf install_development_env.yaml --skip-tags notravis
