language: python
python: "2.7"

sudo: enabled
dist: xenial

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.5.1

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
  # Mock ansible.cfg
  - sudo mkdir -p /etc/ansible
  - sudo echo "" > /etc/ansible/ansible.cfg

script:
  - ansible-playbook -i inventory/hf install_development_env.yaml --syntax-check
  - sudo ansible-playbook -i inventory/hf install_development_env.yaml
