---

- name: get spotify deb gpg keys
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: install spotify deb repo
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
  
- name: install spotify
  apt:
   name: spotify-client
   state: latest
   update_cache: yes

