---
#- name: "create dev user"
#  user:
#    name: "{{ user.username }}"
#    group: "{{ user.group }}"
#    home: "{{ user.home_path}}"
#    state: present

- name: "configure standard editor vim"
  shell: update-alternatives --set editor /usr/bin/vim.basic

- name: "copy users bashrc"
  template:
    src: "bashrc"
    dest: "{{ user.home_path }}/.bashrc" 

- name: "copy tmux conf"
  template:
    src: "tmux_conf"
    dest: "{{ user.home_path }}/.tmux.conf" 

- name: "copy users bashrc"
  template:
    src: "profile"
    dest: "{{ user.home_path }}/.profile" 

- name: "copy vimrc"
  template:
    src: "vimrc"
    dest: "/etc/vim/vimrc" 

- name: "copy users bash_logout"
  template:
    src: "bash_logout"
    dest: "{{ user.home_path }}/.bash_logout" 
