---
- name: "copy users bashrc"
  template:
    src: "bashrc"
    dest: "{{ user.home_path }}/.bashrc" 

- name: "copy tmux conf"
  template:
    src: "tmux_conf"
    dest: "{{ path.tmux.config }}"

- name: "copy users bashrc"
  template:
    src: "profile"
    dest: "{{ user.home_path }}/.profile" 

- name: "copy vimrc"
  template:
    src: "vimrc.j2"
    dest: "{{ path.vim.config }}"

- name: "copy users bash_logout"
  template:
    src: "bash_logout"
    dest: "{{ user.home_path }}/.bash_logout" 
