---
- name: Fetch Skype for Linux
  get_url:
    url: https://repo.skype.com/latest/skypeforlinux-64.deb
    dest: /tmp/skypeforlinux-64.deb

- name: get keys for skype
    shell: "curl https://repo.skype.com/data/SKYPE-GPG-KEY | sudo apt-key add -"

- name: Install Skype for Linux
  apt:
    deb: /tmp/skypeforlinux-64.deb

# Does not work like in http://docs.ansible.com/ansible/apt_module.html ?
#- name: Fetch and install Skype for Linux
#  apt:
#    deb: https://repo.skype.com/latest/skypeforlinux-64.deb 

- name: cleanup installation 1/3
  file:
    path: /tmp/skypeforlinux-64.deb
    state: absent

-name: cleanup installation 2/3
    shell: add-apt-repository --remove skype-stable

- name: cleanup installation 3/3
  file: 
    path: /etc/apt/sources.list.d/skype-stable.list
    state: absent
    
