---

- name: Set power profile on high
  cron:
    name: "4k100hz_power_setting"
    special_time: reboot
#    job: 'sleep 3; echo "low" > /sys/class/drm/card0/device/power_dpm_force_performance_level'
    job: 'sleep 3; echo "high" > /sys/class/drm/card0/device/power_dpm_force_performance_level'
    user: root
