---

- name: update ubuntu
  apt:
    upgrade: dist

- name: install basic packages for daily use
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - tmux
    - atop
    - ssh
    - vim
    - tree
    - curl
    - git
    - python3
    - python3-pip
    - p7zip-full
    - keepassx
    - sysstat
    - iftop
    - lm-sensors
    - xsel
