---
- name: add pycharm repo to deb list
  apt_repository:
    repo: deb http://archive.getdeb.net/ubuntu yakkety-getdeb apps
    state: present

- name: add keyring for pycharm repo
  apt_key:
    url: http://archive.getdeb.net/getdeb-archive.key
    state: present

- name: update ubuntu
  apt:
    upgrade: dist

- name: install basic packages for daily use
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - tmux
    - atop
    - ssh
    - vim
    - tree
    - curl
    - ack-grep
    - git
    - python3
    - python3-pip
    - redshift
    - redshift-gtk
    - compizconfig-settings-manager
    - compiz-plugins
    - p7zip-full
    - qemu-kvm
    - libvirt-bin 
    - ubuntu-vm-builder
    - bridge-utils
    - keepassx
    - pycharm
    - sysstat

- name: Add user to libvirt and kvm
  user:
    name: "{{ user.username }}"
    groups: libvirtd,kvm
    state: present

- name: create tmux directory
  file:
    path: "{{ user.home_path }}/.tmux"
    state: directory
    owner: "{{ user.username }}"
    group: "{{ user.username }}"

- name: Clone Tmux plugins
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ user.home_path }}/.tmux/plugins/tpm"
  become: true
  become_user: "{{ user.username }}"

- name: Clone Tmux ressurect
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: "{{ user.home_path }}/.tmux/plugins/resurrect"
  become: true
  become_user: "{{ user.username }}"

