---

- name: Install KVM
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - qemu-kvm
    - libvirt-bin
    - ubuntu-vm-builder
    - bridge-utils
    - virt-manager

- name: add user to libvirt and kvm
  user:
    name: "{{ user.username }}"
    groups: libvirtd,kvm,adm
    state: present
