---

- name: Download Microsoft VSCode Deb package
  get_url:
    url: "https://go.microsoft.com/fwlink/?LinkID=760868"
    dest: /tmp/vscode.deb
    mode: '0755'
  become_user: "{{ user.username }}"
  become: yes

- name: Install Microsoft VSCode
  apt:
    deb: "/tmp/vscode.deb"
    state: present
  become_user: root
  become: yes

- name: Cleanup installation package
  file:
    path: "/tmp/vscode.deb"
    state: absent
