syntax on
set showmatch
set ignorecase
set incsearch
set nocompatible
set encoding=utf8
set wildmenu
set autoread
set hlsearch
set smartcase
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set pastetoggle=<F9>
set number
set relativenumber
set incsearch
set autoindent
let python_highlight_all = 1
colo ron
set runtimepath=~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/after
set backspace=indent,eol,start

