---

- name: Create Pycharm folder
  file:
    path: "{{ user.home_path }}/pycharm"
    state: directory

- name: Fetch Pycharm 2018.1.4 from direct link
  get_url:
    url: https://download.jetbrains.com/python/pycharm-community-2018.1.4.tar.gz
    dest: "{{ user.home_path }}/pycharm/pycharm_ce_2018.1.4.tar.gz"
    mode: "0775"

- name: Unarchive Pycharm
  unarchive:
    src: "{{ user.home_path }}/pycharm/pycharm_ce_2018.1.4.tar.gz"
    dest: "{{ user.home_path }}/pycharm/"

- name: Clean up Pycharm folder
  file:
    path: "{{ user.home_path }}/pycharm/pycharm_ce_2018.1.4.tar.gz"
    state: absent

- name: Start Pycharm
  shell: "{{ user.home_path }}/pycharm/pycharm-community-2018.1.4/bin/pycharm.sh"